"""customer fields on handover

Revision ID: 5453b5aded5a
Revises: 81b573e5491c
Create Date: 2026-05-10 11:29:21.284422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5453b5aded5a'
down_revision: Union[str, Sequence[str], None] = '81b573e5491c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('handover_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contact_person', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(), nullable=True))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('handover_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('contact_person')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
