"""add region to handover

Revision ID: 81b573e5491c
Revises: 785e03059370
Create Date: 2026-05-10 11:20:25.229342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b573e5491c'
down_revision: Union[str, Sequence[str], None] = '785e03059370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('handover_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('handover_records', schema=None) as batch_op:
        batch_op.drop_column('region')

    # ### end Alembic commands ###
